apiVersion: v1
kind: Pod
metadata:
  name: mqtt-sender
  # Namespace must match IoT MQ BrokerListener's namespace
  # Otherwise use the long hostname: aio-mq-dmqtt-frontend.azure-iot-operations.svc.cluster.local
  namespace: azure-iot-operations
spec:
  # Use the "mqtt-client" service account which comes with default deployment
  # Otherwise create it with `kubectl create serviceaccount mqtt-client -n azure-iot-operations`
  serviceAccountName: mqtt-client
  containers:
  - image: deviomt.azurecr.io/iomtplatformmqtt:latest
    name: mqtt-sender
    env:
    - name: TcpServer_Server
      value: "aio-mq-dmqtt-frontend"
    - name: TcpServer_Port
      value: "8883"
    - name: Content_Type
      value: "application/json"
    - name: Topic_Name
      value: "test1"
    - name: Credential_UserName
      value: "$sat"
    - name: Credential_Password
      value: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImpQNVl6WDU1bWRJUnFuOGNZOVJPcm9jUVBPOE5RN1gya2pBLUJ6MC1RQncifQ.eyJhdWQiOlsiYWlvLW1xIl0sImV4cCI6MTcwMzczNzQ4NCwiaWF0IjoxNzAzNjUxMDg0LCJpc3MiOiJodHRwczovL2Frcy1kZXYtaW9tdC1wb2MtZWFzdHVzMi1kbnMtZDU3M3BxZW0uaGNwLmVhc3R1czIuYXptazhzLmlvIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJhenVyZS1pb3Qtb3BlcmF0aW9ucyIsInBvZCI6eyJuYW1lIjoibXF0dC1jbGllbnQiLCJ1aWQiOiJhZmI1MjZkOS00OWQ3LTQyNjQtOTUwMy1jOTY5M2U1ODI0OTMifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im1xdHQtY2xpZW50IiwidWlkIjoiOTNiZThhY2UtZDIzZi00MTMxLWI0YzUtOTQ5NjA2ZjllNjU1In19LCJuYmYiOjE3MDM2NTEwODQsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphenVyZS1pb3Qtb3BlcmF0aW9uczptcXR0LWNsaWVudCJ9.yDJz1mnDi9l6cr2wlNz0UST54e37TZxnd52vYerbLFab1pAlI9lm4FgaRQ1XFnuIKREpeBJTvAGexSGWou2PBUStRWhP-WZt88B6JUEKmY7QY3lLHsUmT0lhnTm0V3Hn6yjoksTqFxp-OAmQwGWW6kpM3rRx3VQQj3-g_pFQbUfQm0ziKAUXHGg4ev_OUH53mYNOUKzkhrgjPf8aE4rZgS49QO9Sp5xkdzNE8bhMilJ92Z_Xp0D8aaL98GlxQdqqQNinbNgPZ2a9s2nR-R3eRdyioeTsCzv1SoEGSNvuHLtlD9zcjHFos3Ixoh5XqgnK0VtH_h1Dgb9nRo5bURyipOO1EU5OijXKQFAwslf_MR-9AIpy9QyN7jCouB6x7upUidJ9Yj-PsAhjtYCeTfCUaZP13njXy3lY0x4HacFUbVsYV2Qtra7BRWxPOfwkSwtD7sAX3fINkm9rKsZPL5-fm_gZmBDUx9QxOZha-UdQRwC0ZAd0Vd4TjypmmTi-cw-BcLs7-0GkMcpTEmo7NreF_bRxDtQzTkkDy0h7TdA9VWpoufJKsgybrRAZK7XoG69lSYeVDAbMlCXwuhg_xf9yRRpydsbIZjFad3hb5ickAQVmbG_wHuYkpR0pK0Ai2583vNg2u6ef6hDB9_xqNpMkG9ezzXkcXtvilkbuzw3ZYHM"
    volumeMounts:
    - name: mq-sat
      mountPath: /var/run/secrets/tokens
    - name: trust-bundle
      mountPath: /var/run/certs
  imagePullSecrets:
  - name: deviomt-acr-secret
  volumes:
  - name: mq-sat
    projected:
      sources:
      - serviceAccountToken:
          path: mq-sat
          audience: aio-mq # Must match audience in BrokerAuthentication
          expirationSeconds: 86400
  - name: trust-bundle
    configMap:
      name: aio-ca-trust-bundle-test-only # Default root CA cert

